export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const STREAM_CREATE = 'STREAM_CREATE'
export const STREAMS_LIST = 'STREAMS_LIST'
export const STREAM_EDIT = 'STREAM_EDIT'
export const STREAM_DELETE = 'STREAM_DELETE'
export const STREAM_GET = 'STREAM_GET'
